@startuml
actor User
boundary Endpoint
control PollutionCollectorCommandHandler
entity eventBus
User -> Endpoint: start pollution collection
Endpoint -> PollutionCollectorCommandHandler: startPollutionCollection
PollutionCollectorCommandHandler -> PollutionCollectorCommandHandler: initializePollutionCollector
PollutionCollectorCommandHandler -> eventBus: publish(PollutionCollectionStartedEvent)

@enduml